### ISSUE TITLE
What stream should I use for rate limiting (i.e. for object mode)?

### ISSUE THREAD

**Issue by sprijk** [maxogden/mississippi#27]

**Comment by bcomnes** [comment]
I think just setting the high water mark will pause stream consumption in object mode. See https://nodejs.org/api/stream.html#stream_buffering

One type of throttling you can add in though, is https://github.com/maxogden/byte-stream which lets you batch up streams by count and time in object mode, or byte count + time not in object mode.

**Comment by bcomnes** [comment]
Didn't mean to close, but please close if that answers your questions.

**Comment by bcomnes** [comment]
Closing.  Speak up if there are unaddressed issues.
