### ISSUE TITLE
pump & concat error handler question

### ISSUE THREAD

**Issue by laduke** [maxogden/mississippi#32]
Hi! 
I refer to the repo all the time; It's great. thanks! Hope this general streams question is OK. 

I noticed that if you pipe/pump into concat-stream, and an error happens before any data passes, 
concat's callback gets called before pipe's error handler. 

So concat's callback gets an empty object, but I don't know if that means "there was no data" or "there was an error". I guess in this instance I'd like to be able to process.exit(1) from the error handler before processing the data, but I could see how in some cases you'd want it the other way around. 

Am I using something wrong? Any tricks?

```
var fs = require('fs')
var miss = require('mississippi')

miss.pipe(
  fs.createReadStream('./nofile'),
  miss.concat(function (result) {
    console.log('concat', result)
  }),
  function () {
    console.log('error handler')
  }
)
```
```
concat 
error handler
```

**Comment by bcomnes** [comment]
The challenge with concat and pump is that you a split callback paths with pump and concat.

Remember the callback on pump isn't just the error handler, it's more accurately dubbed the 'stream ended' or 'stream finished' handler, where you handle the first error thrown by the pipeline, but also handle any outer callbacks with pipeline results or info. 

Any in-memory writable segment should (can?) capture the `result` on the scope outside of the pipeline and then callback from the pump callback with it.  Callbacks/events/properties of the pipeline segments should always be process in the pump callback, and never act as the exit path of the pipeline.  These callbacks should always be though of, resolve and behave as if they are nested inside the pump operation.

```js
var fs = require('fs')
var miss = require('mississippi')

let results
miss.pipe(
  fs.createReadStream('./nofile'),
  miss.concat(function (result) {
    console.log('concat', result)
    results = result
  }),
  function (err) {
    if (err) throw err
    console.log('stream ended')
    console.log(results)
  }
)
```

**Comment by bcomnes** [comment]
One could wire up concat stream and pump to somehow automatically pass results, but this would probably be a non-standard convention on top of the stream API.  Perhaps it could be defined by pump?

**Comment by bcomnes** [comment]
Closing, but we can re-open if there are more questions.

**Comment by laduke** [comment]
> Callbacks/events/properties of the pipeline segments should always be process in the pump callback, and never act as the exit path of the pipeline.

that's the answer!
