### ISSUE TITLE
Include module for connecting streams end-to-end?

### ISSUE THREAD

**Issue by xloem** [maxogden/mississippi#35]
I'm getting a little confused with the terminology of 'pump', 'pipe', and 'concat', but it looks to me like the collection here doesn't provide for gluing streams end-to-end.

Maybe https://www.npmjs.com/package/next-stream would do this?

**Comment by bcomnes** [comment]
Terminology is a tad unfortunate but it sounds like you are looking for 

https://www.npmjs.com/package/pump

Its called 'pipe' in this collection, named after how one uses vanilla node streams:

`readableStreamA.pipe(transformStreamB).pipe(writableStreamC)`

**Comment by bcomnes** [comment]
It looks like next-stream is a specialized readStream that can be created from a series of readStreams.  It should compose well with with this collection and is outside the scope of this collection.  

Closing.  We can reopen if that doesn't answer your question.

**Comment by xloem** [comment]
Sorry, by end-to-end I mean to take many readable streams and turn them into one, such that <<1,2,3>> <<4,5,6>> turns into <<1,2,3,4,5,6>>.  Do you know if this is doable with pump?

**Comment by xloem** [comment]
Sorry, I think you said that's beyond the scope of the collection.  Okay.
