### ISSUE TITLE
Which versions of Node need these utilities?

### ISSUE THREAD

**Issue by jmealo** [maxogden/mississippi#37]
Hello,

Thank you for an awesome collection!

I think it would be helpful to denote in which (if any) versions a fix is present upstream in the documentation.

Stay well,
Jeff

**Comment by bcomnes** [comment]
Do you mean clarify in the documentation a minimum version of node that this collection works with?

**Comment by bcomnes** [comment]
I don't have time or interest to research this, but if someone wants to clarify this in the docs, I'll accept a contribution. Generally though these have been around for a while so they should go back quite a few versions. To be safe, run LTS or greater as always.
