### ISSUE TITLE
Consider adding pump-chain to the collection?

### ISSUE THREAD

**Issue by alessioalex** [maxogden/mississippi#4]
Hey @maxogden !

I made a tiny module that is similar to pump called [pump-chain](https://github.com/alessioalex/pump-chain), but instead of having a callback as the last parameter it bubbles the error from the intermediate streams to the last stream. This is useful when you module pipes multiple streams together and returns an outer stream for end-users to consume.

My real-world use cases for this module: spawning git child_process | parse output | return outer stream. (see 'git-' modules from https://github.com/alessioalex?tab=repositories click on 'sources').

Let me know if you think this is useful. Thanks

**Comment by max-mapper** [comment]
@alessioalex :wave: 

@mafintosh what do you think?

**Comment by mafintosh** [comment]
@alessioalex what would you call the new method? i guess the pipeline method does something similar already (although it also combines all streams into a single one)

**Comment by mafintosh** [comment]
@alessioalex loving the source code of your module btw :)

**Comment by alessioalex** [comment]
@mafintosh the thing is that for the use case of returning a single stream from your lib those module don't seem to help. I needed the error to be triggered on the returned stream so people could catch the error:

```
getStream().on('error', ...
```

In short this is nice for abstracting a lot of piped streams from your module and just act as if there's one stream the user needs to take care of. Providing a callback would seem to defeat that purpose.

/cc @maxogden

**Comment by alessioalex** [comment]
@mafintosh hmm hard question about the naming. pumpChain maybe? :D

**Comment by mafintosh** [comment]
@alessioalex did you see the pipeline method? it is backed by [pumpify](https://github.com/mafintosh/pumpify) and does infact return a single stream with the features you describe above unless I'm misunderstanding you?

**Comment by alessioalex** [comment]
@mafintosh yep you're right. I didn't figure that out the first time from the description. Thanks
