### ISSUE TITLE
Promise-friendly API?

### ISSUE THREAD

**Issue by gmiroshnykov** [maxogden/mississippi#8]
Would you accept a PR that introduces a Promise-friendly API in addition to existing callback API?

E.g. if a callback argument is omitted, a Promise is returned:

```
miss.pipe(stream1, stream2, stream3).then(...).catch(...)
```

but the callback way would still work:

```
miss.pipe(stream1, stream2, stream3, cb)
```

**Comment by max-mapper** [comment]
No thanks, as you can see there is almost no code in this module, it just
exposes the dependencies. I would recommend writing your own module if you
wanna wrap everything

**Comment by gmiroshnykov** [comment]
The fact that this module has almost no code is actually why I thought it would be a good idea :)

A curated meta-module like this one is a great idea!
I use mississippi a lot, but I have to "promisify" it every time so it fits into the rest of my promise-based codebase.
While this approach works just fine, it's one extra layer of boilerplate and I thought I'm not the only one who has to deal with it.

Still, thanks a lot for your work!

**Comment by ralphtheninja** [comment]
> While this approach works just fine, it's one extra layer of boilerplate and I thought I'm not the only one who has to deal with it.

Just make a module `mississippi-promise` or something and publish it to npm :)

**Comment by xloem** [comment]
See https://github.com/bustle/bluestream

**Comment by xloem** [comment]
So, I made https://www.npmjs.com/package/mississippi-promise .  I promisified the functions, wrote a test, and copied and altered the readme from this project.
